//
// Created by cmtheit on 23-7-12.
//

#ifndef COMPUTER_SYSTEMS_A_PROGRAMMERS_PERSPECTIVE_P_H
#define COMPUTER_SYSTEMS_A_PROGRAMMERS_PERSPECTIVE_P_H

int one();

#endif //COMPUTER_SYSTEMS_A_PROGRAMMERS_PERSPECTIVE_P_H
